### ISSUE TITLE
value in sbomasm assemble -t option is not checked

### ISSUE THREAD

**Issue by vargenau** [interlynk-io/sbomasm#78]
From the help page:
```
sbomasm assemble --help
Usage:
  sbomasm assemble [flags]

Flags:
  -t, --type string         product type of the assembled sbom (application, framework, library, container, device, firmware)
```

The string should be checked for the six allowed values.

Currently,
```
sbomasm assemble -n merge -v 1 -t foobar -o merge.spdx.json *.spdx
```
gives no error and produces invalid SPDX.

```
pyspdxtools -i merge.spdx.json
ERROR:root:There have been issues while parsing the provided document:
Error while parsing Package: ['Invalid PrimaryPackagePurpose: foobar']
```

**Comment by riteshnoronha** [comment]
Ok fixed with https://github.com/interlynk-io/sbomasm/pull/79 now u will get a warning if it does not match what SPDX

**Comment by riteshnoronha** [comment]
v0.1.4 has been released with this fix.

**Comment by riteshnoronha** [comment]
@vargenau  we have released a new command for sbomasm called edit. Not sure if you have a use for it, but just wanted to let u know https://github.com/interlynk-io/sbomasm?tab=readme-ov-file#edit

**Comment by vargenau** [comment]
@riteshnoronha 
Thank you, I will give it a try.
But my Homebrew still gets version v0.1.4. did you update it?

**Comment by riteshnoronha** [comment]
@vargenau my bad, just updated it.

**Comment by vargenau** [comment]
> @vargenau my bad, just updated it.

@riteshnoronha 
Thank you, it works now.
